#!/bin/bash
# Switch active SDR radio mode and (re)start the appropriate service.
# Usage: noosphere-radio-mode.sh <mode> <freq> <gain> <ppm> <fips>
# Modes: off | nwr | scanner | rtl433 | aprs
# Only one service runs at a time  -  all others are stopped first.

MODE=${1:-off}
FREQ=${2:-162.550M}
GAIN=${3:-49.6}
PPM=${4:-0}
FIPS=${5:-018005,018013}

ALL_SVC=(noaa-weather scanner-waterfall noosphere-rtl433 noosphere-aprs)

stop_all() {
    for svc in "${ALL_SVC[@]}"; do
        if systemctl is-active --quiet "$svc" 2>/dev/null; then
            systemctl stop "$svc" 2>/dev/null
        fi
    done
}

case "$MODE" in
  off)
    stop_all
    echo "SDR stopped."
    ;;

  nwr)
    stop_all
    # Write runtime config
    mkdir -p /etc/noosphere
    cat > /etc/noosphere/weather.conf <<EOF
FREQ=$FREQ
GAIN=$GAIN
PPM=$PPM
SAME_FIPS=$FIPS
EOF
    systemctl restart noaa-weather.service
    echo "NWR started on $FREQ."
    ;;

  scanner)
    stop_all
    mkdir -p /etc/noosphere
    cat > /etc/noosphere/scanner.conf <<EOF
GAIN=$GAIN
PPM=$PPM
EOF
    systemctl restart scanner-waterfall.service
    echo "Scanner started."
    ;;

  rtl433)
    stop_all
    # rtl433.conf is managed by admin panel (sensor_id/sensor_model)
    # just ensure the bridge is executable and start
    [ -f /usr/local/bin/noosphere-rtl433-bridge.py ] && \
        chmod +x /usr/local/bin/noosphere-rtl433-bridge.py
    systemctl restart noosphere-rtl433.service
    echo "rtl_433 bridge started."
    ;;

  aprs)
    stop_all
    # Regenerate Direwolf config from stored settings
    APRS_FREQ=${APRS_FREQ:-144.3900}
    mkdir -p /etc/noosphere
    cat > /etc/noosphere/direwolf.conf <<EOF
# Direwolf config  -  generated by noosphere-radio-mode.sh
# Receive-only APRS on ${APRS_FREQ} MHz
ADEVICE /dev/stdin
ACHANNELS 1
CHANNEL 0
MYCALL NOCALL
MODEM 1200
EOF
    # Build the rtl_fm pipeline as the ExecStart override
    mkdir -p /etc/systemd/system/noosphere-aprs.service.d
    cat > /etc/systemd/system/noosphere-aprs.service.d/rtlsdr.conf <<EOF
[Service]
ExecStart=
ExecStart=/bin/sh -c 'rtl_fm -f ${APRS_FREQ}M -s 24k -g $GAIN -p $PPM 2>/dev/null | direwolf -c /etc/noosphere/direwolf.conf -r 24000 -t 0 -q hd -'
EOF
    systemctl daemon-reload
    # Also run the APRS packet writer as a separate systemd socket or via direwolf AGW
    # For now Direwolf logs to syslog; a separate watchdog extracts packets
    systemctl restart noosphere-aprs.service
    echo "APRS started on ${APRS_FREQ} MHz."
    ;;

  *)
    echo "Unknown mode: $MODE" >&2
    exit 1
    ;;
esac
